Dragon/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('testdev.urls', namespace='testdev')),
]

testdev/urls.py
from django.conf.urls import url
from . import  views
urlpatterns = [
    #homepage
    url(r'^upload_file/$',views.upload_file,name='upload_file' ),
    url(r'^stressTesting/$',views.stressTesting,name='stressTesting' ),
    url(r'^$',views.index,name='index' ),
    url(r'^test/$',views.test,name='test')
]

testdev/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class TestCase(models.Model):
    #在django中会默认生成可以不用写这行
    #taskdesc, procallcount, amsid, metaruleid, production
    id = models.AutoField(primary_key=True)#用例编号
    taskdesc = models.CharField(max_length=50)
    procallcount = models.CharField(max_length=20)
    amsid = models.CharField(max_length=30)
    metaruleid = models.CharField(max_length=20)
    production = models.CharField(max_length=20)

    def __str__(self):
        return self.taskdesc
    class Meta():#设置缺省值
        #db_table = 'testcase'
        ordering=['id']

testdev/forms.py
#coding:utf8
from django import forms
from django.forms import ModelForm
from django.forms import widgets  # 插件
from django.forms import fields  # 字段
from testdev.models import TestCase

###ContactForm(initial={'subject': 'Hi there!'})
'''
ContactForm(initial={'subject': 'Hi there!'})
f.fields['name'].label = "Username"
nick_name = CharField(required=False)
在子类中，可以通过设置名字为None 来删除从父类中继承的字段。例如：

>>> from django import forms

>>> class ParentForm(forms.Form):
...     name = forms.CharField()
...     age = forms.IntegerField()

>>> class ChildForm(ParentForm):
...     name = None

>>> ChildForm().fields.keys()
... ['age']
IntegerField¶

class IntegerField(**kwargs)¶
默认的Widget：当Field.localize 是False 时为NumberInput，否则为TextInput。
空值：None
规范化为：一个Python 整数或长整数。
验证给定值是一个整数。允许前导和尾随空格，如Python的int()函数。
错误信息的键：required, invalid, max_value, min_value
max_value和min_value错误消息可能包含%(limit_value)s，将替换为适当的限制。

采用两个可选参数进行验证：

max_value¶
min_value¶
它们控制字段中允许的值的范围。
'''
class AaForm(forms.Form):
    name = forms.CharField(30)
    passwrd = forms.CharField(30)
    openid = forms.CharField(30)
    roleid = forms.CharField(30)
    areaid =forms.CharField(10)


class GailvForm(forms.Form):
    pid = forms.CharField(30)
    uin = forms.CharField(30)
    sum = forms.CharField(30)
    areaid = forms.CharField(30)
    roleid=forms.CharField(30)
    url=forms.CharField(30)


class AcForm(forms.Form):
    openid = forms.CharField(30)
    roleid = forms.CharField(30)
    areaid = forms.CharField(10)


class AddTestCaseForm(ModelForm):
    class Meta:
        model = TestCase
        fields = ['taskdesc', 'procallcount', 'amsid', 'metaruleid', 'production']


class GetTestCaseForm(forms.Form):
    production = forms.CharField(
        initial=3,  # 初始值为3
        widget=widgets.Select(choices=((1,'xxsy'), (2,'tlbb'),(3,'all')))  # 插件表现形式为下拉框
        #choices=((1, 'xxsy'), (2, 'tlbb'),),  # 定义下拉框的选项，元祖第一个值为option的value值，后面为html里面的值
        #initial=1,  # 默认选中第二个option
        #widget=widgets.RadioSelect  # 插件表现形式为单选按钮
    )


class StressTestingForm(forms.Form):
    file = forms.FileField(label='上传用户号码包')
    uri = forms.URLField(label='*uri',
                         widget=forms.TextInput(
                             attrs={'placeholder': '示例：https://cgidev.datamore.qq.com/datamore/dnfcityfriend_external/profile'})
                         )
    method = forms.CharField(label='*选择请求方式',
                             initial=1,  # 初始值为1
                             widget=widgets.Select(choices=((1, 'get'), (2, 'post')))
                             )
    parms = forms.CharField(label='设置请求参数',
                            widget=forms.TextInput(
                                attrs={'placeholder': '示例：{"zoneid":"0","matchid":"8","index":"9"}'}),
                            required=False)
    headers = forms.CharField(label='设置header',
                              widget=forms.TextInput(
                                  attrs={'placeholder': '示例：{"cookie": "uin=o0783184998;skey=@FOPCE2Pap"}'}),
                              required=False)
    pos = forms.CharField(label='*用户信息所在位置',
                             initial=1,  # 初始值为1
                             widget=widgets.Select(choices=((1, 'headers'), (2, 'parms')))
                             )
    zhanghao = forms.CharField(label='*用户信息字段',
                               widget=forms.TextInput(
                                   attrs={'placeholder': '多个字段用,隔开，示例：uin,roleid,skey;注：字段顺序与用户包的列排序一致'})
                               )
    nub = forms.IntegerField(label='*最高并发数',
                             max_value=500,
                             min_value=10,
                             widget=forms.TextInput(attrs=
                                                    {'placeholder': '填写大于等于10，小于等于500的整数'})
                             )


class UploadFileForm(forms.Form):
    file = forms.FileField(label='上传用户号码包')
    uri = forms.URLField(label='*uri',
                         widget=forms.TextInput(
                             attrs={'placeholder': '示例：https://cgidev.datamore.qq.com/datamore/dnfcityfriend_external/profile'})
                         )
    method = forms.CharField(label='*选择请求方式',
                             initial=1,  # 初始值为1
                             widget=widgets.Select(choices=((1, 'get'), (2, 'post')))
                             )
    parms = forms.CharField(label='设置请求参数',
                            widget=forms.TextInput(
                                attrs={'placeholder': '示例：{"zoneid":"0","matchid":"8","index":"9"}'}),
                            required=False)
    headers = forms.CharField(label='设置header',
                              widget=forms.TextInput(
                                  attrs={'placeholder': '示例：{"cookie": "uin=o0783184998;skey=@FOPCE2Pap"}'}),
                              required=False)
    tofileds = forms.CharField(label='*目标字段',
                               widget=forms.TextInput(
                                   attrs={'placeholder': '多个字段用,隔开，示例：Data.sgp,Data.dgp,Data.tgp'}),
                               )

    pos = forms.CharField(label='*用户信息所在位置',
                             initial=1,  # 初始值为1
                             widget=widgets.Select(choices=((1, 'headers'), (2, 'parms')))
                             )
    zhanghao = forms.CharField(label='*用户信息字段',
                               widget=forms.TextInput(
                                   attrs={'placeholder': '多个字段用,隔开，示例：uin,roleid,skey;注：字段顺序与用户包的列排序一致'})
                               )
    floattoint = forms.IntegerField(label='转换倍数',
                                    widget=forms.TextInput(
                                        attrs={'placeholder': '3.54转354，此处填写100'}),
                                    required=False
                                    )
    nub = forms.IntegerField(label='*最高并发数',
                             max_value=500,
                             min_value=10,
                             widget=forms.TextInput(attrs=
                                                    {'placeholder': '填写大于等于10，小于等于500的整数'})
                             )

testdev/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json,time,threading,datetime
import Queue,ast
import copy
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse,StreamingHttpResponse
from django.shortcuts import render
from forms import StressTestingForm,UploadFileForm
from testdev.myfunction.bingfa import run
from testdev.myfunction.duolie import req,getduoliedata



# Create your views here.
def index(request):
    return render(request,'index.html')

def stressTesting(request):
    if request.method == 'POST':  # 当提交表单时
        form = StressTestingForm(request.POST, request.FILES)
        method_dict = {'1': 'get', '2': 'post'}
        if form.is_valid():
            # 获取表单数据
            file_from = request.FILES['file']
            uri = form.cleaned_data['uri']
            method = method_dict[form.cleaned_data['method']]
            zhanghao = form.cleaned_data['zhanghao'].split(",")
            iparms = form.cleaned_data['parms']
            iheaders = form.cleaned_data['headers']
            pos = form.cleaned_data['pos']
            nub = form.cleaned_data['nub']
            # 处理表单数据兼容后台程序
            if len(iparms) == 0:
                parms = {}
            else:
                parms = ast.literal_eval(iparms)
            if len(iheaders) == 0:
                headers = {}
            else:
                headers = ast.literal_eval(iheaders)
            #f_to_list = list(set(file_from.readlines()))  # 读取上传文件数据
            f_to_list = file_from.readlines()
            keydata = {}
            err = []
            L_responsetime = []
            starttime = datetime.datetime.now()
            def list_iterator(L):
                """迭代器，分段读取自定义并发线程"""
                sum = len(L)
                n = 0
                while sum > n:
                    l = L[n:n + nub - 1]
                    n = n + nub - 1
                    yield l

            def run(uin, parms1, headers1):
                try:
                    r = req(uri, method, parms=parms1, headers=headers1)
                    ResponseTime = float(r.elapsed.microseconds) / 1000
                    if r.status_code != 200:
                        err.append("code!=200")
                        L_responsetime.append(ResponseTime)
                    else:
                        L_responsetime.append(ResponseTime)
                except:
                    err.append('err')

            for x in list_iterator(f_to_list):
                threads = []  # 线程池
                for a in x:
                    M = a.strip().split(',')  # 账号列的值集合
                    if pos == "1":  # 用户信息位置在header中
                        D_headers = {}
                        scookie = ';'.join(map(lambda x: x + '=%s', zhanghao))  # 格式化cookie
                        D_headers['cookie'] = scookie % tuple(M)
                        headers.update(D_headers)
                    if pos == "2":  # 用户信息位置在parms中
                        D_parms = {k: v for k, v in zip(zhanghao, M)}  # list转dict
                        parms.update(D_parms)  #
                    t = threading.Thread(target=run, args=( M[0], parms.copy(), headers.copy()))  # copy深拷贝父对象（一级目录），子对象（二级目录）不拷贝，还是引用
                    threads.append(t)
                    t.start()
                for T in threads:
                    T.join()
                print "done"
            endtime = datetime.datetime.now()
            AverageTime = "{:.3f}".format(float(sum(L_responsetime)) / float(len(L_responsetime)))  # 计算数组的平均值，保留3位小数
            usetime = str(endtime - starttime)
            hour = usetime.split(':').pop(0)
            minute = usetime.split(':').pop(1)
            second = usetime.split(':').pop(2)
            totaltime = float(hour) * 60 * 60 + float(minute) * 60 + float(second)  # 计算总的思考时间+请求时间
            qps = int(len(f_to_list) / totaltime)
            keydata["request_start_time"] = str(starttime)
            keydata["request_end_time"] = str(endtime)
            keydata["request_max_time"] = max(L_responsetime)
            keydata["request_min_time"] = min(L_responsetime)
            keydata["Average_Response_Time"] = AverageTime
            keydata["qps"] = qps
            keydata["Concurrent_processing"] = nub
            keydata["use_total_time"] = totaltime
            keydata["fail_request"] = err.count("code!=200")
            r = keydata
    else:  # 当正常访问时
        form = StressTestingForm()
        r = {}
    context = {'form':form,'r':r}
    return render(request, 'stressTesting.html',context)

def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST,request.FILES)
        method_dict = {'1': 'get', '2': 'post'}
        print '提交开始时间：',time.ctime()
        if form.is_valid():
            #获取表单数据
            file_from = request.FILES['file']
            uri = form.cleaned_data['uri']
            method = method_dict[form.cleaned_data['method']]
            zhanghao = form.cleaned_data['zhanghao'].split(",")
            tofileds = tuple(form.cleaned_data['tofileds'].split(","))
            iparms = form.cleaned_data['parms']
            iheaders = form.cleaned_data['headers']
            pos = form.cleaned_data['pos']
            floattoint = form.cleaned_data['floattoint']
            nub = form.cleaned_data['nub']
            #处理表单数据兼容后台程序
            if floattoint is None:
                floattoint =1
            if len(iparms) ==0:
                parms = {}
            else:
                parms = ast.literal_eval(iparms)
            if len(iheaders) ==0:
                headers = {}
            else:
                headers = ast.literal_eval(iheaders)
            #多列数据写入路径
            filename = str(time.time()).split('.')[0]+'.txt'
            file_abs = "D:\\autotest\\duoliebag\\"+filename
            #f_to_list = list(set(file_from.readlines()))#读取上传文件数据
            f_to_list = file_from.readlines()
            queue = Queue.Queue()# 数据队列

            def list_iterator(L):
                """迭代器，分段读取自定义并发线程"""
                sum = len(L)
                n = 0
                while sum > n:
                    l = L[n:n + nub-1]
                    n = n + nub-1
                    yield l

            def write(queue, file_abs):
                """写队列数据至文件"""
                with open(file_abs, 'a+') as file_to:
                    while True:
                        line = queue.get()
                        if line == "":
                            break
                        file_to.write(line)

            def run(queue, uin, parms1, headers1):
                #lock.acquire()
                try:
                    r = req(uri, method, parms=parms1, headers=headers1)
                    if r.status_code != 200:
                        f = lambda x: x.encode('utf8') if isinstance(x, unicode) else x
                        L_tofileds = map(lambda x:-2147483648,form.cleaned_data['tofileds'].split(","))
                        L_tofileds.insert(0,f(uin))
                        r1 = str(L_tofileds)
                        r2 = r1.strip('[').strip(']').replace('\'','').replace(' ','')
                    else:
                        r = r.json()
                        r1 = str(getduoliedata(uin, r,floattoint, *tofileds))
                        r2 = r1.strip("[").strip("]").replace('\'','').replace(' ','')
                    queue.put(r2 + '\n')
                except:
                    queue.put("err" + '\n')
                #finally:
                    #lock.release()

            def file_iterator(file_name, chunk_size=512):
                '''文件读取迭代器'''
                with open(file_name) as f:
                    while True:
                        c = f.read(chunk_size)
                        if c:
                            yield c
                        else:
                            break

            write_thread = threading.Thread(target=write, args=(queue, file_abs))
            write_thread.start()
            for x in list_iterator(f_to_list):
                threads = []  #线程池
                for a in x:
                    M = a.strip().split(',')#账号列的值集合
                    if pos == "1":#用户信息位置在header中
                        D_headers= {}
                        scookie = ';'.join(map(lambda x: x+'=%s',zhanghao))#格式化cookie
                        D_headers['cookie'] = scookie % tuple(M)
                        headers.update(D_headers)
                    if pos == "2": #用户信息位置在parms中
                        D_parms={k:v for k,v in zip(zhanghao,M)}#list转dict
                        parms.update(D_parms)#
                    t = threading.Thread(target=run, args=(queue,M[0],parms.copy(),headers.copy()))#copy深拷贝父对象（一级目录），子对象（二级目录）不拷贝，还是引用
                    threads.append(t)
                    t.start()
                for T in threads:
                    T.join()
                print "done"

            queue.put("")
            write_thread.join()
            print '文件完成时间：',time.ctime()
            response = StreamingHttpResponse(file_iterator(file_abs))
            response['Content-Type'] = 'application/octet-stream'
            response['Content-Disposition'] = 'attachment;filename="{0}"'.format(filename)
            return response

    else:
        form = UploadFileForm()
    return render(request,'upload_file.html',{"form":form})

def test(request):
    dict = {"retCode": 0,"retInfo": "成功","data": {"callBack": "aferDmMetricApi","resultData": 0,
                                                  "rdhp": "rc20.dc.DCMETA.db:50020","rau": "redis@dc"}}
    J = json.dumps(dict)
    return HttpResponse(J)

testdev/templates/testdev/addTestCase.html
{% extends "testdev/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2> 新增任务规则测试用例</h2>
{% endblock header %}
{% block content %}
  <form action="{% url 'testdev:addTestCase' %}" method = 'post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">确认提交</button>
    {% endbuttons %}
     <p><a href="{% url 'testdev:getTestCase' %}">返回</a></p>
  </form>
{% endblock content%}

testdev/templates/testdev/alltask.html
{% extends "testdev/base.html" %}
{% block header %}
  <h2> Allactivetasks</h2>
{% endblock header %}
   <寻仙手游活跃任务查询页面>
{% block content %}
    <div id ='result' style="width:100%;margin:10px;">
        <table class ='table table-bordered'>
            <thead>
                <tr>
                    <th>任务编号</th>
                    <th>任务名称</th>
                    <th>任务标的</th>
                    <th>任务进度</th>
                    <th>任务完成情况</th>
                </tr>
            </thead>
            {% for a in r %}
            <tbody>
                <td>{{ a.id }}</td>
                <td>{{ a.desc }}</td>
                <td>{{ a.procAllCount }}</td>
                <td>{{ a.procCount }}</td>
                <td>{{ a.finished }}</td>
            {% empty %}
                There are no entries for this topic yet.
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

testdev/templates/testdev/alterdata.html
{% extends "testdev/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2> Complete The Mission</h2>
{% endblock header %}
{% block content%}
  <form action="{% url 'testdev:alterdata' %}" method = 'post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">commit</button>
    {% endbuttons %}
  </form>

{% endblock content%}

testdev/templates/testdev/base.html
{% load bootstrap3 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
      <link rel="icon" href="{% static 'img/logo.jpg' %}" type="image/x-icon">
      <link rel="shortcut icon" href="{% static 'img/logo.jpg' %}" type="image/x-icon">
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <title>自动化测试工具</title>
      {% bootstrap_css %}
      {% bootstrap_javascript %}
  </head>
  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'testdev:index' %}">Api Test Tools</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'testdev:upload_file' %}">多列包生成工具</a>
                    </li>
                    <li>
                        <a href="{% url 'testdev:stressTesting' %}">接口压测工具</a>
                    </li>


                </ul>
            </div><!-- /.nav-collpase -->

        </div>
    </nav>

    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock %}
        </div>
    </div><!-- /container -->
  </body>
</html>

testdev/templates/testdev/gailvTesting.html
{% extends "testdev/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Task Recommend</h2>
{% endblock header %}
{% block content %}
    <form action="{% url 'testdev:probability' %}" method = 'post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">commit</button>
    {% endbuttons %}
  </form>
{% endblock content%}

testdev/templates/testdev/getTestCase.html
{% extends "testdev/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>测试用例查询页面</h2>
{% endblock header %}
{% block content %}
    <form action="{% url 'testdev:getTestCase' %}" method = 'post' class="form" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button name="submit" class="btn btn-primary">点击查询</button>
      {% endbuttons %}
    </form>
    <a href="{% url 'testdev:addTestCase' %}">新增测试用例</a>
    <div id ='result' style="width:100%;margin:0px;">
        <table class ='table table-bordered'>
            <thead>
                <tr>
                    <th>业务名称</th>
                    <th>用例编号</th>
                    <th>任务名称</th>
                    <th>预期任务标的</th>
                    <th>预期礼包配置</th>
                    <th>指标元数据</th>
                    <th>用例操作</th>
                </tr>
            </thead>
            {% for a in r %}
            <tbody>
                <td>{{ a.production }}</td>
                <td>{{ a.id }}</td>
                <td>{{ a.taskdesc }}</td>
                <td>{{ a.procallcount }}</td>
                <td>{{ a.amsid }}</td>
                <td>{{ a.metaruleid }}</td>
                <td><a href="{% url 'testdev:delTestCase' %}?id={{a.id}}" >编辑</a>
                    <a href="{% url 'testdev:delTestCase' %}?id={{a.id}}" >执行</a>
                    <a href="{% url 'testdev:delTestCase' %}?id={{a.id}}" >删除</a>
                </td>
            {% empty %}

            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

testdev/templates/testdev/index.html
{% extends "testdev/base.html" %}
{% block header  %}
    <div class="jumbotron">
      <h1>Api Test Tools .</h1>
    </div>
{% endblock %}
{% block content %}
    <h3>
    <a href="{% url 'testdev:upload_file' %}">多列包生成工具</a>
    </h3>

{% endblock content %}

testdev/templates/testdev/stressTesting.html
{% extends "testdev/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>压力测试工具</h2>
{% endblock header %}
{% block content %}
    <h3>压测任务配置</h3>
    <form action="{% url 'testdev:stressTesting' %}" method='post' class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">提交</button>
    {% endbuttons %}
    </form>

    <h3>压测任务结果表</h3>
    <div id ='result'  style="width:100%;margin:0px;">
        <table class ='table table-bordered'>
            <thead>
                <tr>
                    <th>并发开始时间</th>
                    <th>并发结束时间</th>
                    <th>最大响应时长(ms)</th>
                    <th>最小响应时长(ms)</th>
                    <th>平均响应时长(ms)</th>
                    <th>QPS</th>
                    <th>总请求数</th>
                    <th>总耗时(s)</th>
                    <th>请求失败数</th>
                </tr>
            </thead>
            <tbody>
                <td>{{ r.request_start_time }}</td>
                <td>{{ r.request_end_time }}</td>
                <td>{{ r.request_max_time }}</td>
                <td>{{ r.request_min_time }}</td>
                <td>{{ r.Average_Response_Time }}</td>
                <td>{{ r.qps }}</td>
                <td>{{ r.Concurrent_processing }}</td>
                <td>{{ r.use_total_time }}</td>
                <td>{{ r.fail_request }}</td>
            </tbody>
        </table>
    </div>
{% endblock content%}

testdev/templates/testdev/upload_file.html
{% extends "testdev/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>多列包生成工具</h2>
{% endblock header %}
{% block content %}
    <form action="{% url 'testdev:upload_file' %}" method = 'post' class="form" enctype="multipart/form-data" >
    {% csrf_token %}
        <h3>一·基本信息填写</h3>
    {% bootstrap_field form.file %}
    {% bootstrap_field form.uri %}
    {% bootstrap_field form.method %}
    {% bootstrap_field form.headers %}
    {% bootstrap_field form.parms %}
    {% bootstrap_field form.pos %}
    {% bootstrap_field form.zhanghao %}
        <h3>二·其他信息填写</h3>
    {% bootstrap_field form.tofileds %}
    {% bootstrap_field form.floattoint %}
    {% bootstrap_field form.nub %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">开始任务</button>
    {% endbuttons %}
    </form>
{% endblock content%}